services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - HOTPEPPER_API_KEY=${HOTPEPPER_API_KEY}
    command: npm run dev -- -H 0.0.0.0
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
            - .next/
        - action: rebuild
          path: ./frontend/package.json