services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - HOTPEPPER_API_KEY=${HOTPEPPER_API_KEY}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    # ホットリロードを有効にするための設定
    command: npm run dev -- -H 0.0.0.0